### ISSUE TITLE
PC Solver acts weird for solid initial row with space beneath it

### ISSUE THREAD

**Issue by JJCUBER** [wirelyre/tetra-tools#1]
Whenever you have a full solid row in the initial field, it drops down to the bottom of the field in each of the possible solves.  The pieces within the possible solves don't shift up after the full solid row is moved to the bottom, so said pieces get partially covered.  In some cases, depending on where the solid row in the initial field is, a gap is formed in the middle of pieces.

Some examples:
![image](https://user-images.githubusercontent.com/34446698/163902007-dbbe0e75-1a79-4e5a-ab84-865374c3ecbb.png)
![image](https://user-images.githubusercontent.com/34446698/163902072-5c518633-7aec-4316-b2d0-2dcc33836bd5.png)
![image](https://user-images.githubusercontent.com/34446698/163902542-405ee18e-a13b-486b-bbcb-00e4dcc68e8c.png)

How they "should" look (if we were to assume that the solid row dropping to the bottom is intentional):
![image](https://user-images.githubusercontent.com/34446698/163903000-e1f740a4-6247-40eb-8959-1fcf530eea57.png)
![image](https://user-images.githubusercontent.com/34446698/163903072-b319fbd7-9f33-4a4b-8704-17bc59101f87.png)

**Comment by wirelyre** [comment]
This should be fixed in f2ca37bdc13f09292280f670e8b5e07054cc2bb9, I just haven't gotten around to updating the online version yet.

In case you're curious, during searches, filled lines always move to the bottom. It's only when making the pictures that they stay in the same place.

Thanks for the report!
